In [1]:
import numpy as np

In [2]:
my_arr = np.array([[1,2,3,4],[5,6,7,8]])
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### indexing한 변수의 value 변경

In [3]:
sub_arr = my_arr[0]
sub_arr

array([1, 2, 3, 4])

In [4]:
sub_arr[2] = 500
my_arr # my_arr의 value도 함께 변한다.

array([[  1,   2, 500,   4],
       [  5,   6,   7,   8]])

#### 함수를 활용한 indexing 변수의 value 변경

In [5]:
a,b = np.hsplit(my_arr,2)

In [6]:
print(a,"\n----------")
print(b)

[[1 2]
 [5 6]] 
----------
[[500   4]
 [  7   8]]


In [7]:
a[0][0] = 100
my_arr # my_arr의 value도 함께 변한다.

array([[100,   2, 500,   4],
       [  5,   6,   7,   8]])