In [2]:
import numpy as np

In [2]:
test = np.array([1,4,5,8],float)
print(test)
print(type(test))
type(test[0])

[ 1.  4.  5.  8.]
<class 'numpy.ndarray'>


numpy.float64

## numpy는 C로 구현되었기 때문에 연산속도가 빠르다.
## 단점은 dynamic programming을 포기

## numpy는 하나의 데이터 종류만 가능 ( R에서 matrix )

In [3]:
test = np.array([1,4,5,"8"],float) # String 8을 float로 변환
print(test)
test.dtype # 타입 확인

[ 1.  4.  5.  8.]


dtype('float64')

In [4]:
a = np.array([[1,2,3],[4.5,5,6]],int)
print(a)
print(a[0,0]) # 0,0 형식을 지원한다.
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [5]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
b[:, 2:] # 모든 행, 2열부터 모두

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [7]:
b[1, 1:3] # 1행 , 열은 1부터 2까지

array([7, 8])

## 함수 활용

In [8]:
print(np.arange(30)) # arange : range와 비슷하다.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [9]:
np.arange(30).reshape(5,6) # reshape(5,6) : 5행 6열의 matrix를 만들어라

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
np.zeros(30) # zero matrix

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [11]:
zeroMat = np.zeros((2,5), np.float32) # 2X5 matrix & 타입 설정
zeroMat

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [12]:
zeroMat.ndim # row 기준 차원의 크기

2

In [13]:
zeroMat.shape # 전체 크기

(2, 5)

In [14]:
np.ones(10) # 1만 들어있는 matrix

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
np.empty(10) # 0처럼 보이지만 값이 없는 matrix

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
np.eye(3,4) # m X n 대각행렬 diagonal matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [17]:
np.identity(5) # n X n 행렬에 diagonal

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## 연산

In [32]:
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [20]:
test_a+test_a

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [28]:
test_a.T  # transpose
test_a.transpose()

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

In [29]:
test_a * test_a  # 같은 위치끼리 곱하는 연산

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

### dot product

In [31]:
test_a.dot(test_a.T)  # dot product 연산방법

array([[ 14.,  32.],
       [ 32.,  77.]])

### 스칼라 연산

In [33]:
test_a+5

array([[  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [34]:
test_a*5

array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

### 비교 연산

In [35]:
test_a = np.array([4,2,5],float)
test_b = np.array([7,1,0],float)

In [36]:
test_a > test_b

array([False,  True,  True], dtype=bool)

In [42]:
np.logical_and(test_a>0,test_a<5)  # and 연산

array([ True,  True, False], dtype=bool)

In [43]:
np.logical_or(test_a<0,test_a>3)  # or 연산

array([ True, False,  True], dtype=bool)

In [44]:
np.where(test_a>0, 5, 2)  # 0보다 크면 5 아니면 2를 index에 맞게 생성

array([5, 5, 5])

In [45]:
test_c = np.array([1,np.NaN, np.Inf], float)

In [46]:
np.isnan(test_c)  # NaN 값이 있는가

array([False,  True, False], dtype=bool)

In [47]:
np.isfinite(test_c)  # infinite한 값이 있으면 false

array([ True, False, False], dtype=bool)

## boolean indexing

In [50]:
test_array = np.array([1,5,3,2,4,6],float)
test_array

array([ 1.,  5.,  3.,  2.,  4.,  6.])

In [51]:
test_array[test_array > 2] # 2보다 큰 지 T/F 결과를 바탕으로 해당 index 출력

array([ 5.,  3.,  4.,  6.])

## fancy indexing

In [53]:
test_array2 = np.array([1,5,3,6,1,9,7],float)

In [54]:
index_array = np.array([0,3,2,1,2,3,5,3,2,1],int)

In [56]:
test_array2[index_array] # index_array의 값을 index로 하여 출력

array([ 1.,  6.,  3.,  5.,  3.,  6.,  9.,  6.,  3.,  5.])

In [57]:
test_array3 = np.array([[1,5],[7,3]],float)

row_array = np.array([0,0,1,1], int)
col_array = np.array([1,0,0,1], int)

In [58]:
test_array3[row_array, col_array] # (row, col) index를 활용하여 출력

array([ 5.,  1.,  7.,  3.])

## linear algebra

#### 3x1+x2 = 9 , x1+2x2 = 8

In [4]:
a = np.array([[3,1],[1,2]],float)
b = np.array([9,8])

In [60]:
np.linalg.solve(a,b)

array([ 2.,  3.])

In [63]:
a.dot(np.array([2,3]).T) # 계산 확인

array([ 9.,  8.])

In [6]:
np.linalg.det(a) # determinant 행렬식이 0이 아닐 때 역행렬이 존재

5.0000000000000009

In [5]:
np.linalg.inv(a) # 역행렬 계산

array([[ 0.4, -0.2],
       [-0.2,  0.6]])